[package]
name = "oscore"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.97", default-features = false, features = ["derive", "alloc"] }
serde_cbor = { version = "0.10.1", default-features = false }
serde_bytes = { version = "0.11.1", default-features = false, features = ["alloc"] }
ed25519-dalek = { version = "0.9.1", default-features = false }
sha2 = { version = "0.8.0", default-features = false }
hkdf = "0.8.0"
digest = "0.8.1"

[dev-dependencies]
x25519-dalek = { version = "0.5.2", default-features = false, features = ["u32_backend"] }
